### ISSUE TITLE
`Deprecation warning` in browser console

### ISSUE THREAD

**Issue by ivan-tarasov** [ivan-tarasov/fh-trip-builder#10]
Now in browser console we have deprecation warning
```javascript
moment.min.js:6 Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Arguments: [object Object]
Error
    at Function.createFromInputFallback (http://static.tarasov.ca/trip-builder/vendor/datepicker/moment.min.js:6:2710)
    at oa (http://static.tarasov.ca/trip-builder/vendor/datepicker/moment.min.js:6:10865)
    at Ia (http://static.tarasov.ca/trip-builder/vendor/datepicker/moment.min.js:6:14772)
    at Ha (http://static.tarasov.ca/trip-builder/vendor/datepicker/moment.min.js:6:14633)
    at Ga (http://static.tarasov.ca/trip-builder/vendor/datepicker/moment.min.js:6:14353)
    at Ja (http://static.tarasov.ca/trip-builder/vendor/datepicker/moment.min.js:6:15085)
    at Ka (http://static.tarasov.ca/trip-builder/vendor/datepicker/moment.min.js:6:15119)
    at a (http://static.tarasov.ca/trip-builder/vendor/datepicker/moment.min.js:6:202)
    at HTMLInputElement.<anonymous> (http://static.tarasov.ca/trip-builder/js/global.js:32:22)
    at Function.each (http://code.jquery.com/jquery-3.3.1.min.js:2:2573)
t @ moment.min.js:6
```

This should be fixed

**Comment by ivan-tarasov** [comment]
This issue should be fixed with changing vendor for date picking, but not now
